name: Demo Notification job
on:
 push:
  branches:
   - main  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting GitHub Actions Job"
      - uses: cinotify/github-action@main
        with:
          to: 'srinivasan@vthink.co.in'
          subject: 'S3 Bucket Updated'
          body: 'This is a notification from GitHub actions.'
  
